# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view_remote.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(250, 400)
        MainWindow.setMinimumSize(QtCore.QSize(250, 400))
        MainWindow.setMaximumSize(QtCore.QSize(250, 400))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.power_button = QtWidgets.QPushButton(self.centralwidget)
        self.power_button.setGeometry(QtCore.QRect(80, 170, 75, 23))
        self.power_button.setObjectName("power_button")
        self.volume_up_button = QtWidgets.QPushButton(self.centralwidget)
        self.volume_up_button.setGeometry(QtCore.QRect(40, 220, 41, 41))
        self.volume_up_button.setStyleSheet("QPushButton"
                             "{"
                             "background-color : #D0E7F9;;"
                             "}"
                             "QPushButton::pressed"
                             "{"
                             "background-color : lightgreen;"
                             "}"
                             )
        self.volume_up_button.setObjectName("volume_up_button")
        self.volume_down_button = QtWidgets.QPushButton(self.centralwidget)
        self.volume_down_button.setGeometry(QtCore.QRect(40, 270, 41, 41))
        self.volume_down_button.setStyleSheet("QPushButton"
                                     "{"
                                     "background-color : #D0E7F9;"
                                     "}"
                                     "QPushButton::pressed"
                                     "{"
                                     "background-color : #F4AEAE;"
                                     "}"
                                     )
        self.volume_down_button.setObjectName("volume_down_button")
        self.channel_up_button = QtWidgets.QPushButton(self.centralwidget)
        self.channel_up_button.setGeometry(QtCore.QRect(160, 220, 41, 41))
        self.channel_up_button.setStyleSheet("QPushButton"
                             "{"
                             "background-color : #D0E7F9;;"
                             "}"
                             "QPushButton::pressed"
                             "{"
                             "background-color : lightgreen;"
                             "}"
                             )
        self.channel_up_button.setObjectName("channel_up_button")
        self.channel_down_button = QtWidgets.QPushButton(self.centralwidget)
        self.channel_down_button.setGeometry(QtCore.QRect(160, 270, 41, 41))
        self.channel_down_button.setStyleSheet("QPushButton"
                                     "{"
                                     "background-color : #D0E7F9;"
                                     "}"
                                     "QPushButton::pressed"
                                     "{"
                                     "background-color : #F4AEAE;"
                                     "}"
                                     )
        self.channel_down_button.setObjectName("channel_down_button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 200, 47, 14))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(160, 200, 47, 14))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.mute_button = QtWidgets.QPushButton(self.centralwidget)
        self.mute_button.setGeometry(QtCore.QRect(100, 320, 51, 21))
        self.mute_button.setObjectName("mute_button")
        self.volume_slider = QtWidgets.QSlider(self.centralwidget)
        self.volume_slider.setGeometry(QtCore.QRect(10, 220, 20, 91))
        self.volume_slider.setMaximum(2)
        self.volume_slider.setOrientation(QtCore.Qt.Vertical)
        self.volume_slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.volume_slider.setTickInterval(1)
        self.volume_slider.setObjectName("volume_slider")
        self.tv_screen = QtWidgets.QLabel(self.centralwidget)
        self.tv_screen.setAlignment(QtCore.Qt.AlignCenter)
        self.tv_screen.setGeometry(QtCore.QRect(40, 20, 171, 121))
        self.tv_screen.setText("")
        self.tv_screen.setObjectName("tv_screen")
        self.power_indicator = QtWidgets.QLabel(self.centralwidget)
        self.power_indicator.setGeometry(QtCore.QRect(100, 150, 41, 20))
        self.power_indicator.setText("")
        self.power_indicator.setObjectName("power_indicator")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 250, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TV Remote"))
        self.power_button.setText(_translate("MainWindow", "Power"))
        self.volume_up_button.setText(_translate("MainWindow", "+"))
        self.volume_down_button.setText(_translate("MainWindow", "-"))
        self.channel_up_button.setText(_translate("MainWindow", "+"))
        self.channel_down_button.setText(_translate("MainWindow", "-"))
        self.label.setText(_translate("MainWindow", "Volume"))
        self.label_2.setText(_translate("MainWindow", "Channel"))
        self.mute_button.setText(_translate("MainWindow", "Mute"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
